services:
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - exercisenet
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s

  backend:    
    build: .
    container_name: exercise
    image: exercise
    environment:
      DATABASE_HOST: db
    ports:  
      - 8081:8081 
    networks:
      - exercisenet
    depends_on:
      - db

networks:
  exercisenet:
    driver: bridge