FROM maven:3.9.3-eclipse-temurin-17

RUN apt-get update -q \
    && apt-get install -qy --no-install-recommends openssh-server \
    && sshpass \ 
    && iputils-ping \
    && net-tools \
    && apt-get clean \
    && rm -rf /var/lib/apt