version: '3.8'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - '3306:3306'
    networks:
      - fiducial-net
      
networks:
  fiducial-net:
    driver: bridge
    name: fiducial-net