services:
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    networks:
      - exercisenet
    profiles:
      - all
      - db
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s

  backend:    
    build: .
    container_name: backend
    image: backend
    profiles: 
      - all
      - backend
    environment:
      DATABASE_HOST: db
    ports:  
      - 8081:8081 
    networks:
      - exercisenet
#    depends_on:
#      db:
#        condition: service_healthy

networks:
  exercisenet:
    driver: bridge